import Head from 'next/head';
import styled from 'styled-components';
import Banner from '../components/Banner';
import Movies from '../components/Movies';
import { baseUrl, fetchApi } from '../utils/fetchApi';

export default function Home({movies, trailer}) {
  console.log(trailer)
  console.log(movies)
  return (
      <>
        <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Banner/>
        <h1 className='title'>Movie Lists :</h1>
        <Cart>
          {movies.map((movie, i) => (
            <Movies movie={movie} key={i}/>
          ))}
        </Cart>
        </Container>
      </>
  )
}

const Container = styled.div`
  .title{
        font-size: 1rem;
        margin: 2rem 4rem;
    }
`
const Cart = styled.div`
  width: 85%;
  margin: 0 auto;
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit , minmax(180px, 1fr));
  margin-bottom: 2rem;
`

export const getStaticProps = async () => {
  const res = await fetchApi(`${baseUrl}/api/movies`);
  const movies = res.results;
  const trailer = await fetchApi(`${baseUrl}/api/trailers/61e8a4c3f2eb8ced20633f4a`);
  return{
    props:{
      movies,
      trailer
    }
  }
}
